### ISSUE TITLE
Throw error while inserting row

### ISSUE THREAD

**Issue by vzilnieks** [vzilnieks/android-lesson6-storage#1]
https://github.com/vzilnieks/android-lesson6-storage/blob/0c98a67ec6c437462de519e905d7831790d0658b/app/src/main/java/com/example/vadim/lesson6storage/MainActivity.java#L55

**Comment by taier** [comment]
Remove old app from device/emulator and clear + rebuild project

**Comment by vzilnieks** [comment]
ok thanx
